-- House of Seams: standard pattern catalog seed
-- Run AFTER 011_pattern_profiles.sql. Idempotent (skips existing handles).
-- Kavya creates the matching Shopify products with these EXACT handles
-- (see SHOPIFY_SETUP.md §6); until then each pattern shows as coming soon.

INSERT INTO pattern_profiles
  (shopify_handle, title, category, pattern_type, difficulty, size_range, formats, fabric_notes, whats_included, preview_config, related_design_slugs, sort_order)
VALUES
  ('princess-cut-blouse-pattern', 'Princess Cut Blouse', 'blouse', 'princess_cut', 'intermediate', '32–44 bust', '{"a4": true, "a0": true, "projector": false}'::jsonb, 'Cottons, brocades, and stable silks — the panel seams shape without darts.', '["Layered PDF pattern (A4 + A0)", "Step-by-step illustrated instructions", "Fabric & notions chart", "Seam-allowance included"]'::jsonb, '{"renderer": "blouse", "style": {"neck_style": "round", "back_style": "round", "sleeve_style": "short", "closure": "hook", "embellishment": "plain", "base_color": "#D6A6B1"}}'::jsonb, '["classic-round"]'::jsonb, 1),
  ('single-katori-blouse-pattern', 'Single Katori Blouse', 'blouse', 'single_katori', 'intermediate', '32–44 bust', '{"a4": true, "a0": true, "projector": false}'::jsonb, 'Medium-weight silks and satins; needs a stable lining.', '["Layered PDF pattern (A4 + A0)", "Step-by-step illustrated instructions", "Fabric & notions chart", "Seam-allowance included"]'::jsonb, '{"renderer": "blouse", "style": {"neck_style": "sweetheart", "back_style": "round", "sleeve_style": "short", "closure": "hook", "embellishment": "plain", "base_color": "#B87A88"}}'::jsonb, '["elegant-sweetheart"]'::jsonb, 2),
  ('double-katori-blouse-pattern', 'Double Katori Blouse', 'blouse', 'double_katori', 'advanced', '32–44 bust', '{"a4": true, "a0": true, "projector": false}'::jsonb, 'Structured silks; the two-piece cup rewards careful pressing.', '["Layered PDF pattern (A4 + A0)", "Step-by-step illustrated instructions", "Fabric & notions chart", "Seam-allowance included"]'::jsonb, '{"renderer": "blouse", "style": {"neck_style": "sweetheart", "back_style": "deep-round", "sleeve_style": "short", "closure": "hook", "embellishment": "zari", "base_color": "#A4586A"}}'::jsonb, '["elegant-sweetheart"]'::jsonb, 3),
  ('three-dart-blouse-pattern', 'Three Dart Blouse', 'blouse', 'three_dart', 'beginner', '32–44 bust', '{"a4": true, "a0": true, "projector": false}'::jsonb, 'Forgiving in cottons and cotton-silk — the classic tailor’s cut.', '["Layered PDF pattern (A4 + A0)", "Step-by-step illustrated instructions", "Fabric & notions chart", "Seam-allowance included"]'::jsonb, '{"renderer": "blouse", "style": {"neck_style": "round", "back_style": "round", "sleeve_style": "short", "closure": "hook", "embellishment": "plain", "base_color": "#E7D3AC"}}'::jsonb, '["classic-round"]'::jsonb, 4),
  ('four-dart-blouse-pattern', 'Four Dart Blouse', 'blouse', 'four_dart', 'intermediate', '32–44 bust', '{"a4": true, "a0": true, "projector": false}'::jsonb, 'Close-fitting; best in fabrics with a little body.', '["Layered PDF pattern (A4 + A0)", "Step-by-step illustrated instructions", "Fabric & notions chart", "Seam-allowance included"]'::jsonb, '{"renderer": "blouse", "style": {"neck_style": "square", "back_style": "round", "sleeve_style": "short", "closure": "hook", "embellishment": "plain", "base_color": "#8FA88D"}}'::jsonb, '["stone-studded-square"]'::jsonb, 5),
  ('choli-cut-blouse-pattern', 'Choli Cut Blouse', 'blouse', 'choli_cut', 'intermediate', '32–44 bust', '{"a4": true, "a0": true, "projector": false}'::jsonb, 'Lehenga-ready cropped fit; silks and brocades.', '["Layered PDF pattern (A4 + A0)", "Step-by-step illustrated instructions", "Fabric & notions chart", "Seam-allowance included"]'::jsonb, '{"renderer": "blouse", "style": {"neck_style": "sweetheart", "back_style": "tie", "sleeve_style": "cap", "closure": "hook", "embellishment": "plain", "base_color": "#D6A6B1"}}'::jsonb, '["elegant-sweetheart"]'::jsonb, 6),
  ('deep-round-back-blouse-pattern', 'Deep Round Back Blouse', 'blouse', 'deep_round', 'beginner', '32–44 bust', '{"a4": true, "a0": true, "projector": false}'::jsonb, 'Any stable woven; facing pieces included for the low back.', '["Layered PDF pattern (A4 + A0)", "Step-by-step illustrated instructions", "Fabric & notions chart", "Seam-allowance included"]'::jsonb, '{"renderer": "blouse", "style": {"neck_style": "round", "back_style": "deep-round", "sleeve_style": "short", "closure": "hook", "embellishment": "plain", "base_color": "#B7C9B5"}}'::jsonb, '["classic-round"]'::jsonb, 7),
  ('boat-neck-blouse-pattern', 'Boat Neck Blouse', 'blouse', 'boat_neck', 'intermediate', '32–44 bust', '{"a4": true, "a0": true, "projector": false}'::jsonb, 'Crisp cottons and raw silk hold the wide neckline best.', '["Layered PDF pattern (A4 + A0)", "Step-by-step illustrated instructions", "Fabric & notions chart", "Seam-allowance included"]'::jsonb, '{"renderer": "blouse", "style": {"neck_style": "boat", "back_style": "v", "sleeve_style": "elbow", "closure": "hook", "embellishment": "plain", "base_color": "#2D2D2D"}}'::jsonb, '["boat-neck-minimal"]'::jsonb, 8),
  ('high-neck-blouse-pattern', 'High Neck Blouse', 'blouse', 'high_neck', 'intermediate', '32–44 bust', '{"a4": true, "a0": true, "projector": false}'::jsonb, 'Structured fabrics; collar interfacing guide included.', '["Layered PDF pattern (A4 + A0)", "Step-by-step illustrated instructions", "Fabric & notions chart", "Seam-allowance included"]'::jsonb, '{"renderer": "blouse", "style": {"neck_style": "high", "back_style": "keyhole", "sleeve_style": "elbow", "closure": "hook", "embellishment": "zari", "base_color": "#A4586A"}}'::jsonb, '["regal-zari-high-neck"]'::jsonb, 9),
  ('backless-tie-blouse-pattern', 'Backless Tie Blouse', 'blouse', 'backless_tie', 'advanced', '32–44 bust', '{"a4": true, "a0": true, "projector": false}'::jsonb, 'Soft silks and georgettes; fully lined bodice.', '["Layered PDF pattern (A4 + A0)", "Step-by-step illustrated instructions", "Fabric & notions chart", "Seam-allowance included"]'::jsonb, '{"renderer": "blouse", "style": {"neck_style": "v", "back_style": "tie", "sleeve_style": "sleeveless", "closure": "hook", "embellishment": "plain", "base_color": "#8E4757"}}'::jsonb, '["mirror-work-deep-v"]'::jsonb, 10),
  ('sleeve-block-pack-pattern', 'Sleeve Block Pack (6 styles)', 'blouse', 'sleeve_block', 'beginner', 'Fits all our blouse patterns', '{"a4": true, "a0": true, "projector": false}'::jsonb, 'Six interchangeable sleeves — cap to full — drafted to our blouse armhole.', '["Six sleeve blocks (cap, short, elbow, three-quarter, full, puff)", "Layered PDF (A4 + A0)", "Armhole matching guide"]'::jsonb, '{"renderer": "blouse", "style": {"neck_style": "round", "back_style": "round", "sleeve_style": "full", "closure": "hook", "embellishment": "plain", "base_color": "#F0D4DA"}}'::jsonb, '[]'::jsonb, 11),
  ('a-line-6-kali-lehenga-pattern', '6-Kali A-Line Lehenga', 'lehenga', 'a_line_6kali', 'beginner', 'Waist 26–44', '{"a4": true, "a0": true, "projector": false}'::jsonb, 'Cottons and light silks; gentle sweep, easy first lehenga.', '["Layered PDF pattern (A4 + A0)", "Step-by-step illustrated instructions", "Fabric & notions chart", "Seam-allowance included"]'::jsonb, '{"renderer": "lehenga", "style": {"silhouette": "a_line", "closure": "side_zip", "embellishment": "plain", "base_color": "#D6A6B1"}}'::jsonb, '["classic-a-line"]'::jsonb, 20),
  ('kalidar-lehenga-8-pattern', '8-Kali Lehenga', 'lehenga', 'kalidar_8', 'intermediate', 'Waist 26–44', '{"a4": true, "a0": true, "projector": false}'::jsonb, 'Silks, georgettes, and festive weaves.', '["Layered PDF pattern (A4 + A0)", "Step-by-step illustrated instructions", "Fabric & notions chart", "Seam-allowance included"]'::jsonb, '{"renderer": "lehenga", "style": {"silhouette": "paneled", "closure": "side_zip", "embellishment": "plain", "base_color": "#8FA88D"}}'::jsonb, '["paneled-heritage"]'::jsonb, 21),
  ('kalidar-lehenga-12-pattern', '12-Kali Lehenga', 'lehenga', 'kalidar_12', 'advanced', 'Waist 26–44', '{"a4": true, "a0": true, "projector": false}'::jsonb, 'Twelve panels for serious sweep; be patient with the seams.', '["Layered PDF pattern (A4 + A0)", "Step-by-step illustrated instructions", "Fabric & notions chart", "Seam-allowance included"]'::jsonb, '{"renderer": "lehenga", "style": {"silhouette": "paneled", "closure": "side_zip", "embellishment": "zari", "base_color": "#A4586A"}}'::jsonb, '["paneled-heritage"]'::jsonb, 22),
  ('umbrella-lehenga-pattern', 'Umbrella Cut Lehenga', 'lehenga', 'umbrella', 'intermediate', 'Waist 26–44', '{"a4": true, "a0": true, "projector": false}'::jsonb, 'Flowing georgettes and crepes — maximum twirl.', '["Layered PDF pattern (A4 + A0)", "Step-by-step illustrated instructions", "Fabric & notions chart", "Seam-allowance included"]'::jsonb, '{"renderer": "lehenga", "style": {"silhouette": "circular", "closure": "drawstring", "embellishment": "plain", "base_color": "#B87A88"}}'::jsonb, '["grand-circular-twirl"]'::jsonb, 23),
  ('mermaid-lehenga-pattern', 'Mermaid Lehenga', 'lehenga', 'mermaid', 'advanced', 'Waist 26–44', '{"a4": true, "a0": true, "projector": false}'::jsonb, 'Stretch-free structured fabrics; fitted through the hip and thigh.', '["Layered PDF pattern (A4 + A0)", "Step-by-step illustrated instructions", "Fabric & notions chart", "Seam-allowance included"]'::jsonb, '{"renderer": "lehenga", "style": {"silhouette": "mermaid", "closure": "side_zip", "embellishment": "sequin", "base_color": "#2D2D2D"}}'::jsonb, '["mermaid-muse"]'::jsonb, 24),
  ('sharara-pattern', 'Sharara Pair', 'lehenga', 'sharara', 'intermediate', 'Waist 26–44', '{"a4": true, "a0": true, "projector": false}'::jsonb, 'Soft flowing fabrics; the wide leg reads like a skirt in motion.', '["Layered PDF pattern (A4 + A0)", "Step-by-step illustrated instructions", "Fabric & notions chart", "Seam-allowance included"]'::jsonb, '{"renderer": "bottoms", "style": {"bottom_style": "palazzo", "waistband": "drawstring", "pleats": "none", "base_color": "#A4586A"}}'::jsonb, '[]'::jsonb, 25),
  ('straight-kurti-pattern', 'Straight Kurti', 'kurti', 'straight', 'beginner', 'XS–3XL', '{"a4": true, "a0": true, "projector": true}'::jsonb, 'Cottons, rayons, and linen blends.', '["Layered PDF pattern (A4 + A0)", "Step-by-step illustrated instructions", "Fabric & notions chart", "Seam-allowance included"]'::jsonb, '{"renderer": "kurti", "style": {"cut": "straight", "slit": "side_slits", "neckline": "round", "sleeve_style": "three-quarter", "embellishment": "plain", "base_color": "#8FA88D"}}'::jsonb, '["everyday-straight"]'::jsonb, 30),
  ('a-line-kurti-pattern', 'A-Line Kurti', 'kurti', 'a_line', 'beginner', 'XS–3XL', '{"a4": true, "a0": true, "projector": true}'::jsonb, 'Drapey cottons and rayons skim best.', '["Layered PDF pattern (A4 + A0)", "Step-by-step illustrated instructions", "Fabric & notions chart", "Seam-allowance included"]'::jsonb, '{"renderer": "kurti", "style": {"cut": "a_line", "slit": "side_slits", "neckline": "band", "sleeve_style": "three-quarter", "embellishment": "plain", "base_color": "#B7C9B5"}}'::jsonb, '["boardroom-a-line", "mandarin-muse"]'::jsonb, 31),
  ('flared-kurti-pattern', 'Flared Kurti', 'kurti', 'flared', 'intermediate', 'XS–3XL', '{"a4": true, "a0": true, "projector": false}'::jsonb, 'Light festive fabrics with movement.', '["Layered PDF pattern (A4 + A0)", "Step-by-step illustrated instructions", "Fabric & notions chart", "Seam-allowance included"]'::jsonb, '{"renderer": "kurti", "style": {"cut": "flared", "slit": "none", "neckline": "v", "sleeve_style": "three-quarter", "embellishment": "zari", "base_color": "#A4586A"}}'::jsonb, '["festive-flare"]'::jsonb, 32),
  ('anarkali-kalidar-kurti-pattern', 'Anarkali Kalidar', 'kurti', 'anarkali_kalidar', 'advanced', 'XS–3XL', '{"a4": true, "a0": true, "projector": false}'::jsonb, 'Fitted bodice flowing into kalis — a project to be proud of.', '["Layered PDF pattern (A4 + A0)", "Step-by-step illustrated instructions", "Fabric & notions chart", "Seam-allowance included"]'::jsonb, '{"renderer": "kurti", "style": {"cut": "flared", "slit": "none", "neckline": "sweetheart", "sleeve_style": "full", "embellishment": "embroidery", "base_color": "#8E4757"}}'::jsonb, '[]'::jsonb, 33),
  ('salwar-pattern', 'Classic Salwar', 'bottoms', 'salwar', 'beginner', 'Waist 24–50', '{"a4": true, "a0": true, "projector": false}'::jsonb, 'Soft cottons; pleat guide included.', '["Layered PDF pattern (A4 + A0)", "Step-by-step illustrated instructions", "Fabric & notions chart", "Seam-allowance included"]'::jsonb, '{"renderer": "bottoms", "style": {"bottom_style": "salwar", "waistband": "drawstring", "pleats": "pleated", "base_color": "#8FA88D"}}'::jsonb, '["everyday-salwar"]'::jsonb, 40),
  ('churidar-pattern', 'Churidar', 'bottoms', 'churidar', 'intermediate', 'Waist 24–50', '{"a4": true, "a0": true, "projector": false}'::jsonb, 'Fabrics with slight give; gathers guide for the ankle.', '["Layered PDF pattern (A4 + A0)", "Step-by-step illustrated instructions", "Fabric & notions chart", "Seam-allowance included"]'::jsonb, '{"renderer": "bottoms", "style": {"bottom_style": "churidar", "waistband": "elastic", "pleats": "none", "base_color": "#D6A6B1"}}'::jsonb, '["classic-churidar"]'::jsonb, 41),
  ('palazzo-pattern', 'Palazzo', 'bottoms', 'palazzo', 'beginner', 'Waist 24–50', '{"a4": true, "a0": true, "projector": false}'::jsonb, 'Flowing rayons, crepes, and linen.', '["Layered PDF pattern (A4 + A0)", "Step-by-step illustrated instructions", "Fabric & notions chart", "Seam-allowance included"]'::jsonb, '{"renderer": "bottoms", "style": {"bottom_style": "palazzo", "waistband": "hook", "pleats": "none", "base_color": "#A4586A"}}'::jsonb, '["palazzo-breeze"]'::jsonb, 42),
  ('patiala-pattern', 'Patiala Salwar', 'bottoms', 'patiala', 'advanced', 'Waist 24–50', '{"a4": true, "a0": true, "projector": false}'::jsonb, 'Generous pleats need soft, light fabric — and patience.', '["Layered PDF pattern (A4 + A0)", "Step-by-step illustrated instructions", "Fabric & notions chart", "Seam-allowance included"]'::jsonb, '{"renderer": "bottoms", "style": {"bottom_style": "salwar", "waistband": "drawstring", "pleats": "pleated", "base_color": "#B87A88"}}'::jsonb, '["everyday-salwar"]'::jsonb, 43),
  ('straight-pant-pattern', 'Straight Pant', 'bottoms', 'straight_pant', 'beginner', 'Waist 24–50', '{"a4": true, "a0": true, "projector": false}'::jsonb, 'Suitings and stable cottons for a clean column.', '["Layered PDF pattern (A4 + A0)", "Step-by-step illustrated instructions", "Fabric & notions chart", "Seam-allowance included"]'::jsonb, '{"renderer": "bottoms", "style": {"bottom_style": "straight_pant", "waistband": "hook", "pleats": "none", "base_color": "#2D2D2D"}}'::jsonb, '["tailored-straight"]'::jsonb, 44),
  ('pattu-pavadai-pattern', 'Pattu Pavadai (Kids)', 'pattu_pavadai', 'pattu_pavadai', 'beginner', 'Ages 1–12', '{"a4": true, "a0": true, "projector": false}'::jsonb, 'Pattu silks with a cotton lining; sizes by age with growth room.', '["Layered PDF pattern (ages 1–12)", "Skirt + waistband pieces", "Growth-tuck guide", "Illustrated instructions"]'::jsonb, '{"renderer": "lehenga", "style": {"silhouette": "a_line", "closure": "side_zip", "embellishment": "zari", "base_color": "#A4586A"}}'::jsonb, '[]'::jsonb, 50),
  ('kids-choli-pattern', 'Kids Choli', 'pattu_pavadai', 'kids_choli', 'beginner', 'Ages 1–12', '{"a4": true, "a0": true, "projector": false}'::jsonb, 'Soft cottons and lined pattu; gentle armholes for little arms.', '["Layered PDF pattern (A4 + A0)", "Step-by-step illustrated instructions", "Fabric & notions chart", "Seam-allowance included"]'::jsonb, '{"renderer": "blouse", "style": {"neck_style": "round", "back_style": "round", "sleeve_style": "cap", "closure": "hook", "embellishment": "plain", "base_color": "#D6A6B1"}}'::jsonb, '[]'::jsonb, 51),
  ('bodice-block-pattern', 'Personal Bodice Block', 'foundational', 'bodice_block', 'advanced', 'Drafted to your measurements', '{"a4": true, "a0": false, "projector": false}'::jsonb, 'Draft in muslin first; this is the foundation everything fitted starts from.', '["Draft-along instructions", "Measurement worksheet", "Fitting troubleshooting guide"]'::jsonb, '{"renderer": "blouse", "style": {"neck_style": "high", "back_style": "round", "sleeve_style": "sleeveless", "closure": "hook", "embellishment": "plain", "base_color": "#E7D3AC"}}'::jsonb, '[]'::jsonb, 60),
  ('petticoat-pattern', 'Saree Petticoat', 'foundational', 'petticoat', 'beginner', 'Waist 24–48', '{"a4": true, "a0": true, "projector": false}'::jsonb, 'Cottons and satins; six-panel classic with drawstring waist.', '["Layered PDF pattern (A4 + A0)", "Step-by-step illustrated instructions", "Fabric & notions chart", "Seam-allowance included"]'::jsonb, '{"renderer": "lehenga", "style": {"silhouette": "straight", "closure": "drawstring", "embellishment": "plain", "base_color": "#F0D4DA"}}'::jsonb, '[]'::jsonb, 61)
ON CONFLICT (shopify_handle) DO NOTHING;
