import { BlouseDesign } from '../../types/blouseDesign';
import { MeasurementDefault } from '../../types/measurements';

// Fallback data mirroring supabase/seed.sql, used only when Supabase is
// not configured (same convention as the products page JSON fallback).

export const FALLBACK_DESIGNS: BlouseDesign[] = [
    {
        id: 'fallback-1',
        name: 'Classic Round',
        slug: 'classic-round',
        description: 'A timeless everyday silhouette with a modest round neckline and short sleeves.',
        neckStyle: 'round',
        backStyle: 'round',
        sleeveStyle: 'short',
        closure: 'hook',
        embellishment: 'plain',
        baseColor: '#D6A6B1',
        isActive: true,
        sortOrder: 1,
    },
    {
        id: 'fallback-2',
        name: 'Elegant Sweetheart',
        slug: 'elegant-sweetheart',
        description: 'A romantic sweetheart neckline with a deep round back, perfect for receptions.',
        neckStyle: 'sweetheart',
        backStyle: 'deep-round',
        sleeveStyle: 'cap',
        closure: 'zip',
        embellishment: 'embroidery',
        baseColor: '#B87A88',
        isActive: true,
        sortOrder: 2,
    },
    {
        id: 'fallback-3',
        name: 'Regal Zari High-Neck',
        slug: 'regal-zari-high-neck',
        description: 'A high neckline with rich zari work and elbow sleeves for a stately bridal look.',
        neckStyle: 'high',
        backStyle: 'keyhole',
        sleeveStyle: 'elbow',
        closure: 'button',
        embellishment: 'zari',
        baseColor: '#8FA88D',
        isActive: true,
        sortOrder: 3,
    },
    {
        id: 'fallback-4',
        name: 'Boat Neck Minimal',
        slug: 'boat-neck-minimal',
        description: 'A clean boat neck with three-quarter sleeves for a contemporary festive style.',
        neckStyle: 'boat',
        backStyle: 'v',
        sleeveStyle: 'three-quarter',
        closure: 'zip',
        embellishment: 'plain',
        baseColor: '#2D2D2D',
        isActive: true,
        sortOrder: 4,
    },
    {
        id: 'fallback-5',
        name: 'Mirror-Work Deep V',
        slug: 'mirror-work-deep-v',
        description: 'A statement V-neck with mirror embellishment and a tie back.',
        neckStyle: 'v',
        backStyle: 'tie',
        sleeveStyle: 'sleeveless',
        closure: 'tie',
        embellishment: 'mirror',
        baseColor: '#B7C9B5',
        isActive: true,
        sortOrder: 5,
    },
    {
        id: 'fallback-6',
        name: 'Stone-Studded Square',
        slug: 'stone-studded-square',
        description: 'A square neckline studded with stones, full sleeves for a winter wedding.',
        neckStyle: 'square',
        backStyle: 'round',
        sleeveStyle: 'full',
        closure: 'hook',
        embellishment: 'stone',
        baseColor: '#D6A6B1',
        isActive: true,
        sortOrder: 6,
    },
];

export const FALLBACK_BRACKETS: MeasurementDefault[] = [
    {
        id: 'fallback-b1', label: 'Under 18', ageMin: 13, ageMax: 17,
        bust: 32, waist: 26, shoulderWidth: 13.5, blouseLength: 13.5,
        sleeveLength: 6, armhole: 15, frontNeckDepth: 6, backNeckDepth: 7,
    },
    {
        id: 'fallback-b2', label: '18-25', ageMin: 18, ageMax: 25,
        bust: 34, waist: 28, shoulderWidth: 14, blouseLength: 14,
        sleeveLength: 6, armhole: 15.5, frontNeckDepth: 6.5, backNeckDepth: 7,
    },
    {
        id: 'fallback-b3', label: '26-40', ageMin: 26, ageMax: 40,
        bust: 36, waist: 31, shoulderWidth: 14.5, blouseLength: 14.5,
        sleeveLength: 6.5, armhole: 16.5, frontNeckDepth: 6.5, backNeckDepth: 7.5,
    },
    {
        id: 'fallback-b4', label: '41 and above', ageMin: 41, ageMax: 99,
        bust: 38, waist: 34, shoulderWidth: 15, blouseLength: 15,
        sleeveLength: 7, armhole: 17.5, frontNeckDepth: 6, backNeckDepth: 7,
    },
];
